nohup: ignoring input
/home/wzc/app/paper_to/web
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.250:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-341-091
14.137.153.199 - - [14/Oct/2025 19:56:37] "GET / HTTP/1.1" 200 -
14.137.153.199 - - [14/Oct/2025 19:56:37] "GET /list_environments HTTP/1.1" 200 -
14.137.153.199 - - [14/Oct/2025 19:56:38] "GET /list_prompts?env=Generate_DAG HTTP/1.1" 200 -
14.137.153.199 - - [14/Oct/2025 19:56:38] "GET /list_versions?env=Generate_DAG&prompt=Check_DAG/Check_DAG HTTP/1.1" 200 -
14.137.153.199 - - [14/Oct/2025 20:21:13] "GET / HTTP/1.1" 200 -
14.137.153.199 - - [14/Oct/2025 20:21:16] "GET /list_environments HTTP/1.1" 200 -
14.137.153.199 - - [14/Oct/2025 20:21:18] "GET /list_prompts?env=Generate_DAG HTTP/1.1" 200 -
14.137.153.199 - - [15/Oct/2025 08:48:21] "GET / HTTP/1.1" 200 -
14.137.153.199 - - [15/Oct/2025 08:48:27] "GET /list_environments HTTP/1.1" 200 -
14.137.153.199 - - [15/Oct/2025 08:48:27] "GET /list_prompts?env=Generate_DAG HTTP/1.1" 200 -
14.137.153.199 - - [15/Oct/2025 08:48:28] "GET /list_versions?env=Generate_DAG&prompt=Check_DAG/Check_DAG HTTP/1.1" 200 -
14.137.153.199 - - [15/Oct/2025 08:48:28] "GET /get_prompt?env=Generate_DAG&prompt=Check_DAG/Check_DAG&version=v1 HTTP/1.1" 200 -
 * Detected change in '/home/wzc/app/paper_to/web/src/Generate_DAG/demo.py', reloading
/home/wzc/app/paper_to/web
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-341-091
14.137.135.195 - - [16/Oct/2025 09:42:02] "GET / HTTP/1.1" 200 -
14.137.135.195 - - [16/Oct/2025 09:42:03] "GET /list_environments HTTP/1.1" 200 -
14.137.135.195 - - [16/Oct/2025 09:42:04] "GET /list_prompts?env=Generate_DAG HTTP/1.1" 200 -
14.137.135.195 - - [16/Oct/2025 09:42:05] "GET /list_versions?env=Generate_DAG&prompt=Check_DAG/Check_DAG HTTP/1.1" 200 -
14.137.135.195 - - [16/Oct/2025 09:42:06] "GET /get_prompt?env=Generate_DAG&prompt=Check_DAG/Check_DAG&version=v1 HTTP/1.1" 200 -
14.137.135.195 - - [16/Oct/2025 10:00:08] "GET /list_versions?env=Generate_DAG&prompt=Generate_DAG/Generate_DAG HTTP/1.1" 200 -
14.137.135.195 - - [16/Oct/2025 10:00:09] "GET /get_prompt?env=Generate_DAG&prompt=Generate_DAG/Generate_DAG&version=v1 HTTP/1.1" 200 -
14.137.135.195 - - [16/Oct/2025 10:00:11] "GET /list_versions?env=Generate_DAG&prompt=Read_Paper/Read_Paper HTTP/1.1" 200 -
14.137.135.195 - - [16/Oct/2025 10:00:12] "GET /get_prompt?env=Generate_DAG&prompt=Read_Paper/Read_Paper&version=v1 HTTP/1.1" 200 -
/root/miniconda3/envs/crewai/lib/python3.10/site-packages/pydantic/fields.py:1093: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'required'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/
  warn(
2025-10-16T02:02:15.224Z [38;5;70m[INFO.][0m Agenta - SDK version: 0.50.6 [38;5;245m[agenta.sdk.agenta_init][0m 
2025-10-16 10:02:15,224 - 139950029817664 - _base.py-_base:223 - INFO: 2025-10-16T02:02:15.224Z [38;5;70m[INFO.][0m Agenta - SDK version: 0.50.6 [38;5;245m[agenta.sdk.agenta_init][0m 
2025-10-16T02:02:15.224Z [38;5;70m[INFO.][0m Agenta - Host: https://cloud.agenta.ai [38;5;245m[agenta.sdk.agenta_init][0m 
2025-10-16 10:02:15,224 - 139950029817664 - _base.py-_base:223 - INFO: 2025-10-16T02:02:15.224Z [38;5;70m[INFO.][0m Agenta - Host: https://cloud.agenta.ai [38;5;245m[agenta.sdk.agenta_init][0m 
2025-10-16T02:02:15.224Z [38;5;70m[INFO.][0m Agenta - OLTP URL: https://cloud.agenta.ai/api/otlp/v1/traces [38;5;245m[agenta.sdk.tracing.tracing][0m 
2025-10-16 10:02:15,224 - 139950029817664 - _base.py-_base:223 - INFO: 2025-10-16T02:02:15.224Z [38;5;70m[INFO.][0m Agenta - OLTP URL: https://cloud.agenta.ai/api/otlp/v1/traces [38;5;245m[agenta.sdk.tracing.tracing][0m 
2025-10-16 10:02:15,225 - 139950029817664 - __init__.py-__init__:537 - WARNING: Overriding of current TracerProvider is not allowed
Traceback (most recent call last):
  File "/home/wzc/app/paper_to/web/src/Generate_DAG/demo.py", line 178, in <module>
    main()
  File "/home/wzc/app/paper_to/web/src/Generate_DAG/demo.py", line 151, in main
    agents.append(build_agent(tools))
  File "/home/wzc/app/paper_to/web/src/Generate_DAG/_build_agent.py", line 34, in build_agent
    llm = ChatOpenAI(
  File "/root/miniconda3/envs/crewai/lib/python3.10/site-packages/langchain_core/load/serializable.py", line 130, in __init__
    super().__init__(*args, **kwargs)
  File "/root/miniconda3/envs/crewai/lib/python3.10/site-packages/pydantic/main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
  File "/root/miniconda3/envs/crewai/lib/python3.10/site-packages/langchain_openai/chat_models/base.py", line 578, in validate_environment
    self.root_client = openai.OpenAI(**client_params, **sync_specific)  # type: ignore[arg-type]
  File "/root/miniconda3/envs/crewai/lib/python3.10/site-packages/openai/_client.py", line 130, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
/root/miniconda3/envs/crewai/lib/python3.10/site-packages/pydantic/fields.py:1093: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'required'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/
  warn(
2025-10-16T02:02:16.043Z [38;5;70m[INFO.][0m Agenta - SDK version: 0.50.6 [38;5;245m[agenta.sdk.agenta_init][0m 
2025-10-16 10:02:16,043 - 140081546921792 - _base.py-_base:223 - INFO: 2025-10-16T02:02:16.043Z [38;5;70m[INFO.][0m Agenta - SDK version: 0.50.6 [38;5;245m[agenta.sdk.agenta_init][0m 
2025-10-16T02:02:16.043Z [38;5;70m[INFO.][0m Agenta - Host: https://cloud.agenta.ai [38;5;245m[agenta.sdk.agenta_init][0m 
2025-10-16 10:02:16,043 - 140081546921792 - _base.py-_base:223 - INFO: 2025-10-16T02:02:16.043Z [38;5;70m[INFO.][0m Agenta - Host: https://cloud.agenta.ai [38;5;245m[agenta.sdk.agenta_init][0m 
2025-10-16T02:02:16.043Z [38;5;70m[INFO.][0m Agenta - OLTP URL: https://cloud.agenta.ai/api/otlp/v1/traces [38;5;245m[agenta.sdk.tracing.tracing][0m 
2025-10-16 10:02:16,043 - 140081546921792 - _base.py-_base:223 - INFO: 2025-10-16T02:02:16.043Z [38;5;70m[INFO.][0m Agenta - OLTP URL: https://cloud.agenta.ai/api/otlp/v1/traces [38;5;245m[agenta.sdk.tracing.tracing][0m 
2025-10-16 10:02:16,044 - 140081546921792 - __init__.py-__init__:537 - WARNING: Overriding of current TracerProvider is not allowed
Traceback (most recent call last):
  File "/home/wzc/app/paper_to/web/src/Generate_DAG/demo.py", line 178, in <module>
    main()
  File "/home/wzc/app/paper_to/web/src/Generate_DAG/demo.py", line 151, in main
    agents.append(build_agent(tools))
  File "/home/wzc/app/paper_to/web/src/Generate_DAG/_build_agent.py", line 34, in build_agent
    llm = ChatOpenAI(
  File "/root/miniconda3/envs/crewai/lib/python3.10/site-packages/langchain_core/load/serializable.py", line 130, in __init__
    super().__init__(*args, **kwargs)
  File "/root/miniconda3/envs/crewai/lib/python3.10/site-packages/pydantic/main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
  File "/root/miniconda3/envs/crewai/lib/python3.10/site-packages/langchain_openai/chat_models/base.py", line 578, in validate_environment
    self.root_client = openai.OpenAI(**client_params, **sync_specific)  # type: ignore[arg-type]
  File "/root/miniconda3/envs/crewai/lib/python3.10/site-packages/openai/_client.py", line 130, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
14.137.135.195 - - [16/Oct/2025 10:02:16] "[35m[1mPOST /generate HTTP/1.1[0m" 500 -
14.137.135.195 - - [16/Oct/2025 10:02:17] "[35m[1mPOST /generate HTTP/1.1[0m" 500 -
14.137.135.195 - - [16/Oct/2025 10:02:34] "GET /list_docs?arxiv_id=PP HTTP/1.1" 200 -
14.137.135.195 - - [16/Oct/2025 10:02:35] "GET /get_doc?arxiv_id=PP&filename=phase2_methodology.md HTTP/1.1" 200 -
14.137.135.195 - - [16/Oct/2025 10:02:35] "GET /list_docs?arxiv_id=PP HTTP/1.1" 200 -
14.137.135.195 - - [16/Oct/2025 10:02:36] "GET /get_doc?arxiv_id=PP&filename=phase2_methodology.md HTTP/1.1" 200 -
14.137.135.195 - - [16/Oct/2025 10:03:17] "GET /get_doc?arxiv_id=PP&filename=concise_paper.md HTTP/1.1" 200 -
14.137.135.195 - - [16/Oct/2025 10:03:21] "GET /get_doc?arxiv_id=PP&filename=phase3_experiments.md HTTP/1.1" 200 -
14.137.135.195 - - [16/Oct/2025 10:05:09] "GET /get_doc?arxiv_id=PP&filename=deployment_configuration.json HTTP/1.1" 200 -
14.137.135.195 - - [16/Oct/2025 10:05:11] "GET /get_doc?arxiv_id=PP&filename=phase2_methodology.md HTTP/1.1" 200 -
 * Detected change in '/home/wzc/app/paper_to/web/src/Generate_DAG/_build_agent.py', reloading
/home/wzc/app/paper_to/web
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-341-091
 * Detected change in '/home/wzc/app/paper_to/web/src/Generate_Idea/_build_agent.py', reloading
/home/wzc/app/paper_to/web
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-341-091
 * Detected change in '/home/wzc/app/paper_to/web/src/Generate_DAG/demo.py', reloading
/home/wzc/app/paper_to/web
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-341-091
 * Detected change in '/home/wzc/app/paper_to/web/src/Generate_DAG/demo.py', reloading
/home/wzc/app/paper_to/web
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-341-091
 * Detected change in '/home/wzc/app/paper_to/web/src/Generate_Idea/demo.py', reloading
/home/wzc/app/paper_to/web
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-341-091
 * Detected change in '/home/wzc/app/paper_to/web/src/Generate_DAG/demo.py', reloading
/home/wzc/app/paper_to/web
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-341-091
14.137.135.187 - - [16/Oct/2025 14:56:49] "GET / HTTP/1.1" 200 -
14.137.135.187 - - [16/Oct/2025 14:56:50] "GET /list_environments HTTP/1.1" 200 -
14.137.135.187 - - [16/Oct/2025 14:56:51] "GET /list_prompts?env=Generate_DAG HTTP/1.1" 200 -
14.137.135.187 - - [16/Oct/2025 14:56:52] "GET /list_versions?env=Generate_DAG&prompt=Check_DAG/Check_DAG HTTP/1.1" 200 -
14.137.135.187 - - [16/Oct/2025 14:56:53] "GET /get_prompt?env=Generate_DAG&prompt=Check_DAG/Check_DAG&version=v1 HTTP/1.1" 200 -
14.137.135.187 - - [16/Oct/2025 14:56:53] "GET /list_versions?env=Generate_DAG&prompt=Generate_DAG/Generate_DAG HTTP/1.1" 200 -
14.137.135.187 - - [16/Oct/2025 14:56:54] "GET /get_prompt?env=Generate_DAG&prompt=Generate_DAG/Generate_DAG&version=v1 HTTP/1.1" 200 -
/root/miniconda3/envs/crewai/lib/python3.10/site-packages/pydantic/fields.py:1093: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'required'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/
  warn(
2025-10-16T06:57:07.117Z [38;5;70m[INFO.][0m Agenta - SDK version: 0.50.6 [38;5;245m[agenta.sdk.agenta_init][0m 
2025-10-16 14:57:07,117 - 139817659520832 - _base.py-_base:223 - INFO: 2025-10-16T06:57:07.117Z [38;5;70m[INFO.][0m Agenta - SDK version: 0.50.6 [38;5;245m[agenta.sdk.agenta_init][0m 
2025-10-16T06:57:07.117Z [38;5;70m[INFO.][0m Agenta - Host: https://cloud.agenta.ai [38;5;245m[agenta.sdk.agenta_init][0m 
2025-10-16 14:57:07,117 - 139817659520832 - _base.py-_base:223 - INFO: 2025-10-16T06:57:07.117Z [38;5;70m[INFO.][0m Agenta - Host: https://cloud.agenta.ai [38;5;245m[agenta.sdk.agenta_init][0m 
2025-10-16T06:57:07.117Z [38;5;70m[INFO.][0m Agenta - OLTP URL: https://cloud.agenta.ai/api/otlp/v1/traces [38;5;245m[agenta.sdk.tracing.tracing][0m 
2025-10-16 14:57:07,117 - 139817659520832 - _base.py-_base:223 - INFO: 2025-10-16T06:57:07.117Z [38;5;70m[INFO.][0m Agenta - OLTP URL: https://cloud.agenta.ai/api/otlp/v1/traces [38;5;245m[agenta.sdk.tracing.tracing][0m 
2025-10-16 14:57:07,118 - 139817659520832 - __init__.py-__init__:537 - WARNING: Overriding of current TracerProvider is not allowed
Traceback (most recent call last):
  File "/home/wzc/app/paper_to/web/src/Generate_DAG/demo.py", line 178, in <module>
    main()
  File "/home/wzc/app/paper_to/web/src/Generate_DAG/demo.py", line 151, in main
    agents.append(build_agent("openai/Kimi-K2",tools))
  File "/home/wzc/app/paper_to/web/src/Generate_DAG/_build_agent.py", line 34, in build_agent
    llm = ChatOpenAI(
  File "/root/miniconda3/envs/crewai/lib/python3.10/site-packages/langchain_core/load/serializable.py", line 130, in __init__
    super().__init__(*args, **kwargs)
  File "/root/miniconda3/envs/crewai/lib/python3.10/site-packages/pydantic/main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
  File "/root/miniconda3/envs/crewai/lib/python3.10/site-packages/langchain_openai/chat_models/base.py", line 578, in validate_environment
    self.root_client = openai.OpenAI(**client_params, **sync_specific)  # type: ignore[arg-type]
  File "/root/miniconda3/envs/crewai/lib/python3.10/site-packages/openai/_client.py", line 130, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
14.137.135.187 - - [16/Oct/2025 14:57:08] "[35m[1mPOST /generate HTTP/1.1[0m" 500 -
14.137.135.187 - - [16/Oct/2025 14:57:11] "GET /list_docs?arxiv_id=PP HTTP/1.1" 200 -
14.137.135.187 - - [16/Oct/2025 14:57:12] "GET /get_doc?arxiv_id=PP&filename=phase2_methodology.md HTTP/1.1" 200 -
14.137.135.187 - - [16/Oct/2025 14:57:13] "GET /get_doc?arxiv_id=PP&filename=deployment_configuration.json HTTP/1.1" 200 -
 * Detected change in '/home/wzc/app/paper_to/web/src/Generate_DAG/demo.py', reloading
/home/wzc/app/paper_to/web
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-341-091
 * Detected change in '/home/wzc/app/paper_to/web/src/Generate_DAG/demo.py', reloading
/home/wzc/app/paper_to/web
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-341-091
 * Detected change in '/home/wzc/app/paper_to/web/src/Generate_Idea/demo.py', reloading
/home/wzc/app/paper_to/web
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-341-091
 * Detected change in '/home/wzc/app/paper_to/web/src/Generate_Idea/demo.py', reloading
/home/wzc/app/paper_to/web
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-341-091
14.137.153.199 - - [16/Oct/2025 15:23:45] "GET / HTTP/1.1" 200 -
14.137.153.199 - - [16/Oct/2025 15:23:51] "GET /list_environments HTTP/1.1" 200 -
14.137.153.199 - - [16/Oct/2025 15:23:53] "GET /list_prompts?env=Generate_DAG HTTP/1.1" 200 -
14.137.153.199 - - [16/Oct/2025 15:23:56] "GET /list_versions?env=Generate_DAG&prompt=Check_DAG/Check_DAG HTTP/1.1" 200 -
14.137.153.199 - - [16/Oct/2025 15:23:56] "GET /get_prompt?env=Generate_DAG&prompt=Check_DAG/Check_DAG&version=v1 HTTP/1.1" 200 -
14.137.153.199 - - [16/Oct/2025 15:28:22] "GET / HTTP/1.1" 200 -
14.137.153.199 - - [16/Oct/2025 15:28:22] "GET /list_environments HTTP/1.1" 200 -
14.137.153.199 - - [16/Oct/2025 15:28:23] "GET /list_prompts?env=Generate_DAG HTTP/1.1" 200 -
14.137.153.199 - - [16/Oct/2025 15:28:23] "GET /list_versions?env=Generate_DAG&prompt=Check_DAG/Check_DAG HTTP/1.1" 200 -
14.137.153.199 - - [16/Oct/2025 15:28:24] "GET /get_prompt?env=Generate_DAG&prompt=Check_DAG/Check_DAG&version=v1 HTTP/1.1" 200 -
14.137.153.199 - - [16/Oct/2025 15:28:25] "GET /list_versions?env=Generate_DAG&prompt=Check_Topic/Check_Topic HTTP/1.1" 200 -
14.137.153.199 - - [16/Oct/2025 15:28:26] "GET /get_prompt?env=Generate_DAG&prompt=Check_Topic/Check_Topic&version=v1 HTTP/1.1" 200 -
/root/miniconda3/envs/crewai/lib/python3.10/site-packages/pydantic/fields.py:1093: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'required'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/
  warn(
2025-10-16T07:28:43.070Z [38;5;70m[INFO.][0m Agenta - SDK version: 0.50.6 [38;5;245m[agenta.sdk.agenta_init][0m 
2025-10-16 15:28:43,070 - 139966812780352 - _base.py-_base:223 - INFO: 2025-10-16T07:28:43.070Z [38;5;70m[INFO.][0m Agenta - SDK version: 0.50.6 [38;5;245m[agenta.sdk.agenta_init][0m 
2025-10-16T07:28:43.071Z [38;5;70m[INFO.][0m Agenta - Host: https://cloud.agenta.ai [38;5;245m[agenta.sdk.agenta_init][0m 
2025-10-16 15:28:43,071 - 139966812780352 - _base.py-_base:223 - INFO: 2025-10-16T07:28:43.071Z [38;5;70m[INFO.][0m Agenta - Host: https://cloud.agenta.ai [38;5;245m[agenta.sdk.agenta_init][0m 
2025-10-16T07:28:43.071Z [38;5;70m[INFO.][0m Agenta - OLTP URL: https://cloud.agenta.ai/api/otlp/v1/traces [38;5;245m[agenta.sdk.tracing.tracing][0m 
2025-10-16 15:28:43,071 - 139966812780352 - _base.py-_base:223 - INFO: 2025-10-16T07:28:43.071Z [38;5;70m[INFO.][0m Agenta - OLTP URL: https://cloud.agenta.ai/api/otlp/v1/traces [38;5;245m[agenta.sdk.tracing.tracing][0m 
2025-10-16 15:28:43,071 - 139966812780352 - __init__.py-__init__:537 - WARNING: Overriding of current TracerProvider is not allowed
Traceback (most recent call last):
  File "/home/wzc/app/paper_to/web/src/Generate_DAG/demo.py", line 194, in <module>
    main()
  File "/home/wzc/app/paper_to/web/src/Generate_DAG/demo.py", line 161, in main
    prompt = fetch_prompt_local(variant[k]["slug"], variant[k]["version"], variant[k]["inputs"])
  File "/home/wzc/app/paper_to/web/src/Generate_DAG/demo.py", line 22, in fetch_prompt_local
    with open(f"./src/Generate_DAG/prompts/{slug}/{slug}_{version}.txt","r") as f:
FileNotFoundError: [Errno 2] No such file or directory: './src/Generate_DAG/prompts/Check_Topic/Check_Topic/Check_Topic/Check_Topic_v1.txt'
14.137.153.199 - - [16/Oct/2025 15:28:44] "[35m[1mPOST /generate HTTP/1.1[0m" 500 -
14.137.153.199 - - [16/Oct/2025 15:28:47] "GET /list_docs?arxiv_id=2503.16428v1 HTTP/1.1" 200 -
 * Detected change in '/home/wzc/app/paper_to/web/src/Generate_DAG/demo.py', reloading
/home/wzc/app/paper_to/web
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-341-091
 * Detected change in '/home/wzc/app/paper_to/web/src/Generate_Idea/demo.py', reloading
/home/wzc/app/paper_to/web
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-341-091
 * Detected change in '/home/wzc/app/paper_to/web/src/Generate_Idea/demo.py', reloading
/home/wzc/app/paper_to/web
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-341-091
/root/miniconda3/envs/crewai/lib/python3.10/site-packages/pydantic/fields.py:1093: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'required'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/
  warn(
2025-10-16T07:30:47.196Z [38;5;70m[INFO.][0m Agenta - SDK version: 0.50.6 [38;5;245m[agenta.sdk.agenta_init][0m 
2025-10-16 15:30:47,196 - 140191206664000 - _base.py-_base:223 - INFO: 2025-10-16T07:30:47.196Z [38;5;70m[INFO.][0m Agenta - SDK version: 0.50.6 [38;5;245m[agenta.sdk.agenta_init][0m 
2025-10-16T07:30:47.196Z [38;5;70m[INFO.][0m Agenta - Host: https://cloud.agenta.ai [38;5;245m[agenta.sdk.agenta_init][0m 
2025-10-16 15:30:47,196 - 140191206664000 - _base.py-_base:223 - INFO: 2025-10-16T07:30:47.196Z [38;5;70m[INFO.][0m Agenta - Host: https://cloud.agenta.ai [38;5;245m[agenta.sdk.agenta_init][0m 
2025-10-16T07:30:47.196Z [38;5;70m[INFO.][0m Agenta - OLTP URL: https://cloud.agenta.ai/api/otlp/v1/traces [38;5;245m[agenta.sdk.tracing.tracing][0m 
2025-10-16 15:30:47,196 - 140191206664000 - _base.py-_base:223 - INFO: 2025-10-16T07:30:47.196Z [38;5;70m[INFO.][0m Agenta - OLTP URL: https://cloud.agenta.ai/api/otlp/v1/traces [38;5;245m[agenta.sdk.tracing.tracing][0m 
2025-10-16 15:30:47,196 - 140191206664000 - __init__.py-__init__:537 - WARNING: Overriding of current TracerProvider is not allowed
Traceback (most recent call last):
  File "/home/wzc/app/paper_to/web/src/Generate_DAG/demo.py", line 194, in <module>
    main()
  File "/home/wzc/app/paper_to/web/src/Generate_DAG/demo.py", line 163, in main
    agents.append(build_agent("openai/Kimi-K2",tools))
  File "/home/wzc/app/paper_to/web/src/Generate_DAG/_build_agent.py", line 34, in build_agent
    llm = ChatOpenAI(
  File "/root/miniconda3/envs/crewai/lib/python3.10/site-packages/langchain_core/load/serializable.py", line 130, in __init__
    super().__init__(*args, **kwargs)
  File "/root/miniconda3/envs/crewai/lib/python3.10/site-packages/pydantic/main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
  File "/root/miniconda3/envs/crewai/lib/python3.10/site-packages/langchain_openai/chat_models/base.py", line 578, in validate_environment
    self.root_client = openai.OpenAI(**client_params, **sync_specific)  # type: ignore[arg-type]
  File "/root/miniconda3/envs/crewai/lib/python3.10/site-packages/openai/_client.py", line 130, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
14.137.153.199 - - [16/Oct/2025 15:30:48] "[35m[1mPOST /generate HTTP/1.1[0m" 500 -
14.137.153.199 - - [16/Oct/2025 15:31:02] "GET /list_docs?arxiv_id=2503.16428v1 HTTP/1.1" 200 -
